### ISSUE TITLE
jndi 为什么不能用

### ISSUE THREAD

**Issue by charis3306** [zan8in/afrog#118]
![image](https://github.com/zan8in/afrog/assets/84823804/12cb2469-0aa0-4c4d-b985-d767e800f2f6)
![image](https://github.com/zan8in/afrog/assets/84823804/19140b7f-63ac-4463-980e-0c449f04cff1)
![image](https://github.com/zan8in/afrog/assets/84823804/1ccc9649-6605-4d9f-a00b-8487f0e47475)
内网还是建议使用JNDI,不知道为什么我不能用。

**Comment by zan8in** [comment]
3.0.2之后，旧版 jndi 已废除。

**Comment by charis3306** [comment]
> 3.0.2之后，旧版 jndi 已废除。

可不可以加入，我觉得在内网场景非常好用。

**Comment by zan8in** [comment]
> > 3.0.2之后，旧版 jndi 已废除。
> 
> 
> 
> 可不可以加入，我觉得在内网场景非常好用。

后续考虑加上
