### ISSUE TITLE
不支持https？

### ISSUE THREAD

**Issue by Duke1410** [zan8in/afrog#18]

**Comment by zan8in** [comment]
你是说代理？还是？
afrog 支持 target 自动识别 http(s)

**Comment by Duke1410** [comment]
![图片](https://user-images.githubusercontent.com/104301467/183270724-c6d6245e-5649-4953-9408-03e5bcd35e74.png)
全是http

**Comment by Duke1410** [comment]
> 你是说代理？还是？ afrog 支持 target 自动识别 http(s)

![图片](https://user-images.githubusercontent.com/104301467/183270739-b9b5e55d-5439-4e64-8127-f2130a939999.png)
全是http

**Comment by zan8in** [comment]
最新版会自动识别http,https
扫描目标尽量自带上

**Comment by zan8in** [comment]
@Duke1410 自动识别规则是：先验证 http 协议，可以访问即停止，不再验证 https 协议
