### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by Teicu** [zan8in/afrog#20]
Hello  

can someone show me the steps to install this tool on a MacBook?  
Thanks

**Comment by zan8in** [comment]
download `afrog_arm.tar.gz` if MacBook M1，otherwise download `afrog_macos.tar.gz`

**Comment by Teicu** [comment]
It doesn't work, I've tried both. I'm, using Mac OS Monterey 12.5

**Comment by Teicu** [comment]
Hello,  

I just ran **afrog_macos -t http://testphp.vulnweb.com** and can't find anything. What did I do wrong? because this site is still a test site used for testing and have a lot of flaws 

Thanks

**Comment by Teicu** [comment]
afrog_macos -t http://testphp.vulnweb.com -P afrog/pocs/afrog-pocs  
NAME:
   afrog 漫天星辰 - v1.3.6

PATH:
   /Users/root/.config/afrog/afrog-config.yaml
    v0 (0.1.58)
   /Users/root/afrog/pocs/afrog-pocs
   ./reports/20220802-105849.html

TIPS:
   坚持，是一种品格！

http://testphp.vulnweb.com 200 Home of Acunetix Art 
000 2022-08-02 10:58:50 Fingerprint INFO
649/649 | 100% %

**Comment by Teicu** [comment]
Ok, I scanned again a list of about 700 URLs, the result is the same, no vulnerabilities found by the scanner 

the cmd I used are: 
 
 **frog_macos -T targets.txt -P /afrog/pocs/afrog-pocs**  

and even
 
**frog_macos -T targets.txt -o result.html** 

what's wrong? what am I doing wrong?  

<img width="719" alt="Screenshot 2022-08-02 at 13 51 28" src="https://user-images.githubusercontent.com/1572822/182357685-8d78f976-d7dd-4090-8566-97010b3e7773.png">

Thanks

**Comment by zan8in** [comment]
You search some URLs from shodan, and input to `targets.txt` and run :  **frog_macos -T targets.txt -o r.html**
`shodan-query: http.title:"NS-ASG"`
or
`shodan-query: title:"MinIO Browser"`
