### ISSUE TITLE
install

### ISSUE THREAD

**Issue by pilot-steve** [zan8in/afrog#3]
just an inquiry on how to install considering no documentation is provided

**Comment by zan8in** [comment]
I have released a new version [BUILD-SNAPSHOT 1.2.2](https://github.com/zan8in/afrog/releases/tag/v1.2.2)
**One thing must be done first ：**
delete default config file
`rm -rf ~/.config/afrog/afrog-config.yaml` 
**Then use the program normally**
`./afrog_linux_amd64 -t example.com -o result.html`

**have fun!** #2

**Comment by pilot-steve** [comment]
thank you
