### ISSUE TITLE
I can not run it

### ISSUE THREAD

**Issue by Abdelrahmanibrahim-prog** [zan8in/afrog#52]
Hi,
i setup it using git clone then iam trying to run it but i do not know why or what should i do next.
Any help about the next steps to run it ?

**Comment by zan8in** [comment]
go >= 1.19
Go build cmd/afrog/main.go

**Comment by jarodchang-sudo** [comment]
./main.go: line 1: package: command not found
./main.go: line 3: syntax error near unexpected token `newline'
./main.go: line 3: `import ('

**Comment by zan8in** [comment]
> ./main.go: line 1: package: command not found
> 
> ./main.go: line 3: syntax error near unexpected token `newline'
> 
> ./main.go: line 3: `import ('
> 
> 
> 
> 

I checked that the code is correct and tried git clone again.
