### ISSUE TITLE
./afrog -up更新问题

### ISSUE THREAD

**Issue by szmabcd** [zan8in/afrog#63]
# ./afrog -up更新的时候报如下错误 ，请问下有问题没？

[ERR] `ceye` reverse service not set: /root/.config/afrog/afrog-config.yaml

|       A F R O G       >       2.3.1   -       0.1.99
[FTL] Could not create runner: target not found

**Comment by zan8in** [comment]
你的更新没问题，放心使用。
提示语不友好，下个版本会优化这个问题。

**Comment by zan8in** [comment]
> # ./afrog -up更新的时候报如下错误 ，请问下有问题没？
> [ERR] `ceye` reverse service not set: /root/.config/afrog/afrog-config.yaml
> 
> | A F R O G > 2.3.1 - 0.1.99 [FTL] Could not create runner: target not found

[v2.5.1](https://github.com/zan8in/afrog/releases/tag/v2.5.1)已经修复~

**Comment by 767662409** [comment]
为啥我afrog更新会提示flag provided but not defined: -up
