### ISSUE TITLE
afrog.exe -t http:xxxx像是报错想了解为啥会这样

### ISSUE THREAD

**Issue by HHasi** [zan8in/afrog#66]
Downloading the latest version of afrog-pocs...
panic: flate: corrupt input before offset 5

goroutine 1 [running]:
github.com/zan8in/afrog/pkg/utils.Unzip.extractAndWriteFile.func1()
        github.com/zan8in/afrog/pkg/utils/unzip.go:58 +0x3c
github.com/zan8in/afrog/pkg/utils.Unzip.extractAndWriteFile({}, {0xc000526108, 0x12}, 0xc000542420)
        github.com/zan8in/afrog/pkg/utils/unzip.go:90 +0x3a2
github.com/zan8in/afrog/pkg/utils.Unzip.Extract({}, {0xc00003b1a0?, 0xc000117901?}, {0xc000526108, 0x12})
        github.com/zan8in/afrog/pkg/utils/unzip.go:40 +0x225
github.com/zan8in/afrog/pkg/upgrade.(*Upgrade).Unzip(0xc00016a1e0, {0xc00003b1a0?, 0x101a768?})
        github.com/zan8in/afrog/pkg/upgrade/upgrade.go:133 +0x3d
github.com/zan8in/afrog/pkg/upgrade.(*Upgrade).Download(0xc00016a1e0)
        github.com/zan8in/afrog/pkg/upgrade/upgrade.go:121 +0x9f
github.com/zan8in/afrog/pkg/upgrade.(*Upgrade).UpgradePocs(0xc00016a1e0)
        github.com/zan8in/afrog/pkg/upgrade/upgrade.go:103 +0x10f
github.com/zan8in/afrog/pkg/config.(*Options).verifyOptions(0xc0006041a0)
        github.com/zan8in/afrog/pkg/config/options.go:229 +0x6f0
github.com/zan8in/afrog/pkg/config.NewOptions()
        github.com/zan8in/afrog/pkg/config/options.go:174 +0x1405
main.main()
        ./main.go:26 +0x2e
        
        
        
        会这样子报错

**Comment by ViCrack** [comment]
可能是更新版本出错了吧，你不如手动下载最新的再试

**Comment by zan8in** [comment]
解压报错信息，你再试一次，还报错吗？ @HHasi

**Comment by zan8in** [comment]
> Downloading the latest version of afrog-pocs... panic: flate: corrupt input before offset 5
> 
> goroutine 1 [running]: github.com/zan8in/afrog/pkg/utils.Unzip.extractAndWriteFile.func1() github.com/zan8in/afrog/pkg/utils/unzip.go:58 +0x3c github.com/zan8in/afrog/pkg/utils.Unzip.extractAndWriteFile({}, {0xc000526108, 0x12}, 0xc000542420) github.com/zan8in/afrog/pkg/utils/unzip.go:90 +0x3a2 github.com/zan8in/afrog/pkg/utils.Unzip.Extract({}, {0xc00003b1a0?, 0xc000117901?}, {0xc000526108, 0x12}) github.com/zan8in/afrog/pkg/utils/unzip.go:40 +0x225 github.com/zan8in/afrog/pkg/upgrade.(*Upgrade).Unzip(0xc00016a1e0, {0xc00003b1a0?, 0x101a768?}) github.com/zan8in/afrog/pkg/upgrade/upgrade.go:133 +0x3d github.com/zan8in/afrog/pkg/upgrade.(*Upgrade).Download(0xc00016a1e0) github.com/zan8in/afrog/pkg/upgrade/upgrade.go:121 +0x9f github.com/zan8in/afrog/pkg/upgrade.(*Upgrade).UpgradePocs(0xc00016a1e0) github.com/zan8in/afrog/pkg/upgrade/upgrade.go:103 +0x10f github.com/zan8in/afrog/pkg/config.(*Options).verifyOptions(0xc0006041a0) github.com/zan8in/afrog/pkg/config/options.go:229 +0x6f0 github.com/zan8in/afrog/pkg/config.NewOptions() github.com/zan8in/afrog/pkg/config/options.go:174 +0x1405 main.main() ./main.go:26 +0x2e
> 
> ```
>     会这样子报错
> ```

这个报错可能是由于 afrog-pocs 的 zip 打包出现问题，我已经重新上传 afrog-pocs.zip。现在 afrog 应该可以正常使用了。如果你仍然遇到相同的报错，你可以使用 -duc 命令来禁止 afrog-pocs 的更新检查。

**Comment by HHasi** [comment]
> > 正在下载最新版本的 afrog-pocs... panic: flate: corrupt input before offset 5
> > goroutine 1 [正在运行]：github.com/zan8in/afrog/pkg/utils.Unzip.extractAndWriteFile.func1() github.com/zan8in/afrog/pkg/utils/unzip.go:58 +0x3c github.com/zan8in/ afrog/pkg/utils.Unzip.extractAndWriteFile({}, {0xc000526108, 0x12}, 0xc000542420) github.com/zan8in/afrog/pkg/utils/unzip.go:90 +0x3a2 github.com/zan8in/afrog/pkg/ utils.Unzip.Extract({}, {0xc00003b1a0?, 0xc000117901?}, {0xc000526108, 0x12}) github.com/zan8in/afrog/pkg/utils/unzip.go:40 +0x225 github.com/zan8in/afrog/ pkg/升级。（*升级）。解压缩（0xc00016a1e0，{0xc00003b1a0？，0x101a768？}）github.com/zan8in/afrog/pkg/upgrade/upgrade.go:133 +0x3d github.com/zan8in/afrog/pkg/升级。（*升级）。下载（0xc00016a1e0）github.com/zan8in/afrog/pkg/upgrade/upgrade.go:121 +0x9f github.com/zan8in/afrog/pkg/upgrade。（*升级）.UpgradePocs（0xc00016a1e0 ) github.com/zan8in/afrog/pkg/upgrade/upgrade.go:103 +0x10f github.com/zan8in/afrog/pkg/config.(*选项).verifyOptions(0xc0006041a0) github.com/zan8in/afrog/pkg/config/options.go:229 +0x6f0 github.com/zan8in/afrog /pkg/config.NewOptions() github.com/zan8in/afrog/pkg/config/options.go:174 +0x1405 main.main() ./main.go:26 +0x2e
> > ```
> >     会这样子报错
> > ```
> 
> 这个报错可能是由于afrog-pocs的zip包出现问题，我已经重新上传afrog-pocs.zip。现在afrog应该可以正常使用了。如果你仍然遇到相同的报错，你可以使用 -duc 命令来禁止 afrog -pocs 的更新检查。

好的好的，谢谢蛙哥，我重新试试
