### ISSUE TITLE
扫描相同的资产。老版本2.7.5可以扫描出指纹。新版本2.9.2什么都没有扫描出来。反连平台不配置，跟ceye.io不配置应该没有关系吧。升级之后就啥也扫不到了

### ISSUE THREAD

**Issue by jscdy** [zan8in/afrog#92]
扫描相同的资产。老版本2.7.5可以扫描出指纹。新版本2.9.2什么都没有扫描出来。反连平台不配置，跟ceye.io不配置应该没有关系吧。升级之后就啥也扫不到了

**Comment by zan8in** [comment]
感谢提醒，能加我微信么？[扫描微信](https://github.com/zan8in/afrog#discussion-group)

**Comment by zan8in** [comment]
@jscdy 我确实优化了一部分代码，能加微信提供您说的问题资产么？这对我解决问题非常重要，先谢谢了。
